eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: cloud-getway
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://127.0.0.1:8001/auth/rsa/publicKey
  redis:
    port: 6379
    database: 3
    host: 127.0.0.1
  cloud:
    gateway:
      routes:
        - id: oauth2
          uri: lb://oauth2-serve
          predicates:
            - Path=/auth/**
        - id: website
          uri: lb://website
          predicates:
            - Path=/api-website/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedheader: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
logging:
  level:
    root: info
    com.test.*: debug
secure:
  ignore:
    urls: #配置白名单路径
      - "/auth/oauth/token"
      - "/auth/oauth/check_token"
      - "/auth/rsa/publicKey"
server:
  port: 7171