server:
  port: 8002
  servlet:
    context-path: /api-website/
spring:
  application:
    name: website
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://localhost:8761/eureka

mark: "spring website"
logging:
  level:
    root: info
    com.test.*: debug